export const BOT_PROFILES = [
  {
    id: 'bot_1',
    username: 'FactChecker_9000',
    avatar: '🤖',
    personality: {
      style: 'Precise',
      confidenceRange: [85, 95], // High confidence
      preferredTypes: ['Quick Fact', 'Comparative'],
      claimFrequency: 8000, // ms between claims (slower, more careful)
      difficultyPreference: 'Medium' // Prefers medium difficulty
    }
  },
  {
    id: 'bot_2',
    username: 'TruthSeeker',
    avatar: '🦊',
    personality: {
      style: 'Aggressive',
      confidenceRange: [90, 100], // Very high confidence
      preferredTypes: ['Trend', 'Predictive'],
      claimFrequency: 4000, // Fast submission
      difficultyPreference: 'Hard'
    }
  },
  {
    id: 'bot_3',
    username: 'DebunkKing',
    avatar: '🦅',
    personality: {
      style: 'Skeptical',
      confidenceRange: [70, 85], // Moderate confidence
      preferredTypes: ['Comparative', 'Quick Fact'],
      claimFrequency: 10000, // Slow and careful
      difficultyPreference: 'Hard'
    }
  },
  {
    id: 'bot_4',
    username: 'WikiWarrior',
    avatar: '📚',
    personality: {
      style: 'Academic',
      confidenceRange: [80, 90], // Scholarly confidence
      preferredTypes: ['Quick Fact', 'Comparative'],
      claimFrequency: 7000,
      difficultyPreference: 'Medium'
    }
  },
  {
    id: 'bot_5',
    username: 'CasualChecker',
    avatar: '💎',
    personality: {
      style: 'Casual',
      confidenceRange: [60, 80], // Lower confidence
      preferredTypes: ['Quick Fact'],
      claimFrequency: 6000,
      difficultyPreference: 'Easy'
    }
 }
];

// ============================================
// MASSIVE FACT DATABASE (500+ facts)
// ============================================

export const FACT_DATABASE = {
  'Tech News': {
    Easy: [
      "Apple was founded in 1976 by Steve Jobs, Steve Wozniak, and Ronald Wayne.",
      "Microsoft Windows 1.0 was released in 1985.",
      "Google was founded in September 1998 by Larry Page and Sergey Brin.",
      "The first iPhone was announced by Steve Jobs on January 9, 2007.",
      "Facebook was founded on February 4, 2004, by Mark Zuckerberg.",
      "Amazon was founded by Jeff Bezos in July 1994.",
      "Netflix started as a DVD rental service in 1997.",
      "YouTube was founded in February 2005 by three former PayPal employees.",
      "Twitter was launched in July 2006.",
      "Instagram was created by Kevin Systrom and Mike Krieger in 2010.",
      "The World Wide Web was invented by Tim Berners-Lee in 1989.",
      "The first computer mouse was invented by Douglas Engelbart in 1964.",
      "USB (Universal Serial Bus) was developed in the mid-1990s.",
      "Wi-Fi technology was first released for consumers in 1997.",
      "Bluetooth was named after a 10th-century Danish king, Harald Bluetooth.",
      "The term 'bug' in computing originated from an actual moth found in a computer.",
      "QWERTY keyboard layout was designed in the 1870s.",
      "The '@' symbol in email addresses was chosen by Ray Tomlinson in 1971.",
      "Linux was created by Linus Torvalds in 1991.",
      "Java programming language was released by Sun Microsystems in 1995.",
      "Python was created by Guido van Rossum and released in 1991.",
      "JavaScript was created in just 10 days by Brendan Eich in 1995.",
      "The first website ever created is still online at CERN.",
      "Email predates the World Wide Web by nearly 20 years.",
      "The first domain name ever registered was Symbolics.com in 1985.",
      "CD-ROMs can hold up to 700 MB of data.",
      "The first 1GB hard drive weighed over 500 pounds and cost $40,000.",
      "Moore's Law predicts that transistor count doubles approximately every two years.",
      "The first computer virus was created in 1983 and was called 'Elk Cloner'.",
      "GPS technology was initially developed by the US military.",
      "3D printing technology was invented in the 1980s.",
      "The first text message (SMS) was sent in 1992.",
      "QR codes were invented in Japan in 1994 by Denso Wave.",
      "Touchscreen technology was invented in the 1960s.",
      "The first webcam was used to monitor a coffee pot at Cambridge University.",
      "CAPTCHA stands for 'Completely Automated Public Turing test'.",
      "The first computer to defeat a chess grandmaster was Deep Blue in 1997.",
      "The term 'podcast' combines 'iPod' and 'broadcast'.",
      "Elon Musk co-founded PayPal, which was originally called X.com.",
      "Snapchat was originally called 'Picaboo' when it launched in 2011.",
      "Reddit was founded in 2005 by Steve Huffman and Alexis Ohanian.",
      "Wikipedia was launched on January 15, 2001.",
      "Dropbox was founded in 2007 by Drew Houston and Arash Ferdowsi.",
      "Spotify was founded in 2006 in Stockholm, Sweden.",
      "Tesla was incorporated in July 2003 by Martin Eberhard and Marc Tarpenning.",
      "SpaceX was founded by Elon Musk in 2002.",
      "Uber was founded in 2009 as 'UberCab' in San Francisco.",
      "Airbnb was founded in 2008 in San Francisco.",
      "WhatsApp was founded in 2009 by Brian Acton and Jan Koum.",
      "Zoom was founded in 2011 by Eric Yuan.",
    ],
    Medium: [
      "The first computer bug was an actual moth found in the Harvard Mark II computer in 1947.",
      "Python programming language was named after Monty Python's Flying Circus, not the snake.",
      "The first computer virus in the wild was called 'Elk Cloner' in 1982.",
      "CAPTCHA tests help digitize old books by using words that OCR software couldn't read.",
      "The first 1GB hard drive was released by IBM in 1980 and weighed 550 pounds.",
      "WiFi doesn't stand for 'Wireless Fidelity' - it's just a made-up brand name.",
      "The first email spam was sent in 1978 to 400 recipients on ARPANET.",
      "GIF stands for Graphics Interchange Format and was created in 1987.",
      "The Firefox logo isn't a fox - it's a red panda.",
      "The original name of Windows was 'Interface Manager'.",
      "IBM's Watson is named after IBM's first CEO, Thomas J. Watson.",
      "The first computer programmer was Ada Lovelace in the 1840s.",
      "Siri was originally a standalone app before Apple acquired it in 2010.",
      "Amazon's first name was 'Cadabra' as in 'abracadabra'.",
      "Nokia started as a paper mill company in 1865.",
      "Samsung's first product was dried fish, vegetables and noodles.",
      "Sony's first product was an electric rice cooker that didn't work properly.",
      "HP (Hewlett-Packard) was founded in a garage that's now a California Historical Landmark.",
      "The domain Google.com was registered on September 15, 1997.",
      "Facebook's original color scheme is blue because Mark Zuckerberg is red-green colorblind.",
      "The Twitter bird's official name is Larry, named after basketball player Larry Bird.",
      "YouTube's first video was uploaded on April 23, 2005, titled 'Me at the zoo'.",
      "Instagram was initially called 'Burbn' before pivoting to photo-sharing.",
      "Snapchat's ghost mascot is named Ghostface Chillah.",
      "Reddit's alien mascot is called Snoo.",
      "LinkedIn was founded in the living room of Reid Hoffman in 2002.",
      "PayPal was originally designed to beam money between Palm Pilots.",
      "Skype was originally called 'Sky peer-to-peer' shortened to Skyper then Skype.",
      "Mozilla Firefox was originally called Phoenix, then Firebird.",
      "Opera browser was originally a research project at Norway's Telenor in 1994.",
      "The Bitcoin whitepaper was published in 2008 by someone using the pseudonym Satoshi Nakamoto.",
      "Ethereum was proposed in 2013 by Vitalik Buterin.",
      "The first Bitcoin transaction was for two pizzas worth 10,000 BTC in 2010.",
      "NFT stands for Non-Fungible Token and gained mainstream attention in 2021.",
      "The term 'cloud computing' was likely inspired by cloud symbols in network diagrams.",
      "Deepfake technology uses deep learning and fake to create synthetic media.",
      "The first autonomous robot vacuum was Roomba, released in 2002.",
      "Face ID on iPhone uses over 30,000 infrared dots to map your face.",
      "5G networks can theoretically achieve speeds up to 10 Gbps.",
      "Quantum computers use qubits instead of traditional bits.",
      "The first smartphone, IBM Simon, was released in 1994.",
      "Android's version names were alphabetically ordered desserts until Android 10.",
      "iOS was originally called iPhone OS until 2010.",
      "MacOS was originally called Mac OS X, with X being the Roman numeral for 10.",
      "Chrome browser was first released in 2008 as a beta for Windows.",
      "VPN stands for Virtual Private Network.",
      "RAM stands for Random Access Memory.",
      "SSD stands for Solid State Drive.",
      "CPU stands for Central Processing Unit.",
      "GPU stands for Graphics Processing Unit.",
    ],
    Hard: [
      "The P versus NP problem is one of the seven Millennium Prize Problems worth $1 million.",
      "Quantum computers use qubits that exist in superposition states until measured.",
      "The RSA encryption algorithm is based on the difficulty of factoring large prime numbers.",
      "Moore's Law states that transistor count doubles approximately every two years.",
      "The Turing Test was proposed by Alan Turing in 1950 to test machine intelligence.",
      "Shannon's information theory established the theoretical limits of data compression.",
      "The Byzantine Generals Problem addresses consensus in distributed systems with failures.",
      "CAP theorem states distributed systems can only guarantee two of: Consistency, Availability, Partition tolerance.",
      "MapReduce is a programming model developed by Google for processing large data sets.",
      "ACID properties in databases: Atomicity, Consistency, Isolation, Durability.",
      "The halting problem proves that no algorithm can determine if programs will finish running.",
      "Big O notation describes the worst-case time complexity of algorithms.",
      "Dijkstra's algorithm finds shortest paths in weighted graphs.",
      "The traveling salesman problem is NP-complete.",
      "Public-key cryptography was invented by Whitfield Diffie and Martin Hellman in 1976.",
      "TCP uses a three-way handshake to establish connections.",
      "IPv6 uses 128-bit addresses compared to IPv4's 32-bit addresses.",
      "DNS operates primarily on UDP port 53.",
      "HTTPS uses TLS/SSL for encryption on port 443.",
      "OAuth 2.0 is an authorization framework for token-based authentication.",
      "REST APIs are stateless and use HTTP methods like GET, POST, PUT, DELETE.",
      "GraphQL was developed by Facebook and released in 2015.",
      "WebAssembly enables near-native performance in web browsers.",
      "Service workers enable offline functionality in Progressive Web Apps.",
      "Docker containers share the host OS kernel unlike virtual machines.",
      "Kubernetes automates container orchestration and scaling.",
      "Microservices architecture breaks applications into small, independent services.",
      "CQRS separates read and write operations in application architecture.",
      "Event sourcing stores state changes as a sequence of events.",
      "Lambda calculus is the mathematical foundation of functional programming.",
      "Garbage collection automatically manages memory deallocation.",
      "JIT compilation converts bytecode to machine code at runtime.",
      "Sharding distributes data across multiple database instances.",
      "Eventually consistent systems prioritize availability over immediate consistency.",
      "Merkle trees enable efficient verification of data integrity in blockchains.",
      "Zero-knowledge proofs allow proving knowledge without revealing information.",
      "Homomorphic encryption enables computation on encrypted data.",
      "Differential privacy adds noise to protect individual data in datasets.",
      "Federated learning trains models across decentralized devices.",
      "Transformer architecture revolutionized natural language processing in 2017.",
      "BERT uses bidirectional training for language understanding.",
      "GPT models use autoregressive language modeling.",
      "Convolutional Neural Networks excel at image recognition tasks.",
      "Recurrent Neural Networks process sequential data.",
      "Generative Adversarial Networks pit generator and discriminator networks.",
      "Reinforcement learning uses reward signals to train agents.",
      "Transfer learning applies pre-trained models to new tasks.",
      "Backpropagation computes gradients for neural network training.",
      "Gradient descent optimizes model parameters iteratively.",
      "Overfitting occurs when models memorize training data instead of learning patterns.",
    ]
  },
  
  'Science': {
    Easy: [
      "Water boils at 100 degrees Celsius (212°F) at sea level.",
      "The Earth revolves around the Sun, not the other way around.",
      "DNA stands for Deoxyribonucleic acid.",
      "The speed of light is approximately 299,792 kilometers per second.",
      "Humans have 46 chromosomes in 23 pairs.",
      "The human body has 206 bones.",
      "Plants produce oxygen through photosynthesis.",
      "Gravity causes objects to fall toward Earth.",
      "The Earth is approximately 4.5 billion years old.",
      "Diamonds are made of carbon.",
      "Sound travels faster through water than air.",
      "The human heart beats about 100,000 times per day.",
      "Blood is red because of iron in hemoglobin.",
      "The largest organ in the human body is the skin.",
      "Sharks have no bones - their skeleton is made of cartilage.",
      "Lightning is hotter than the surface of the Sun.",
      "Gold is the only metal that doesn't rust.",
      "The smallest bone in the human body is in the ear.",
      "Octopuses have three hearts.",
      "Honey never spoils - archaeologists found edible honey in Egyptian tombs.",
      "A single bolt of lightning contains enough energy to toast 100,000 slices of bread.",
      "Your brain uses 20% of your body's oxygen and calories.",
      "Stomach acid is strong enough to dissolve razor blades.",
      "You share 50% of your DNA with bananas.",
      "Hot water freezes faster than cold water (Mpemba effect).",
      "A day on Venus is longer than its year.",
      "Neutron stars are so dense a teaspoon would weigh 6 billion tons.",
      "The Milky Way galaxy contains 100-400 billion stars.",
      "The Universe is approximately 13.8 billion years old.",
      "Black holes have gravity so strong that not even light can escape.",
      "The Sun accounts for 99.86% of the mass in our solar system.",
      "Mars has the largest volcano in our solar system, Olympus Mons.",
      "Jupiter's Great Red Spot is a storm that has raged for at least 400 years.",
      "Saturn's rings are made primarily of ice particles.",
      "Pluto was reclassified from planet to dwarf planet in 2006.",
      "The International Space Station orbits Earth every 90 minutes.",
      "The Moon is moving away from Earth at about 3.8 cm per year.",
      "Humans have been to the Moon six times between 1969 and 1972.",
      "The coldest temperature ever recorded on Earth was -128.6°F in Antarctica.",
      "The Sahara Desert is the largest hot desert in the world.",
      "Mount Everest is the tallest mountain on Earth at 8,849 meters.",
      "The deepest point in the ocean is the Mariana Trench at 11,034 meters.",
      "Water covers 71% of Earth's surface.",
      "The Amazon rainforest produces 20% of the world's oxygen.",
      "Earthquakes occur when tectonic plates shift.",
      "Tsunamis are caused by underwater earthquakes or volcanic eruptions.",
      "Hurricanes rotate counterclockwise in the Northern Hemisphere.",
      "The ozone layer protects Earth from ultraviolet radiation.",
      "Carbon dioxide is a greenhouse gas contributing to climate change.",
      "Plastic takes hundreds of years to decompose.",
    ],
    Medium: [
      "The Heisenberg Uncertainty Principle states you cannot know both position and momentum precisely.",
      "E=mc² shows the equivalence of mass and energy.",
      "The strong nuclear force holds atomic nuclei together.",
      "Antimatter annihilates regular matter on contact, releasing pure energy.",
      "Schrödinger's cat thought experiment explores quantum superposition.",
      "The double-slit experiment demonstrates wave-particle duality.",
      "Entropy always increases in isolated systems (Second Law of Thermodynamics).",
      "Absolute zero is -273.15°C, where molecular motion stops.",
      "Superconductors have zero electrical resistance below critical temperature.",
      "Bose-Einstein condensates are a fifth state of matter.",
      "Quantum entanglement allows instantaneous correlation between particles.",
      "The Pauli Exclusion Principle prevents identical fermions from occupying same state.",
      "Hawking radiation causes black holes to slowly evaporate.",
      "The Chandrasekhar limit is 1.4 solar masses for white dwarf stability.",
      "Pulsars are rapidly rotating neutron stars that emit radiation beams.",
      "Dark matter accounts for 27% of the universe's mass-energy.",
      "Dark energy comprises 68% of the universe's mass-energy.",
      "The cosmic microwave background is radiation from the Big Bang.",
      "Red shift indicates galaxies are moving away from us.",
      "The observable universe is 93 billion light-years in diameter.",
      "CRISPR-Cas9 is a gene-editing technology discovered in bacteria.",
      "Telomeres protect chromosomes and shorten with each cell division.",
      "Mitochondria have their own DNA separate from nuclear DNA.",
      "Prokaryotic cells lack a nucleus, unlike eukaryotic cells.",
      "Stem cells can differentiate into various cell types.",
      "The human genome contains approximately 3 billion base pairs.",
      "Only 1-2% of human DNA codes for proteins.",
      "Epigenetics studies heritable changes without DNA sequence alterations.",
      "The gut microbiome contains trillions of bacteria.",
      "Antibiotics kill bacteria but are ineffective against viruses.",
      "Vaccines work by training the immune system to recognize pathogens.",
      "mRNA vaccines instruct cells to produce viral proteins.",
      "Prions are misfolded proteins that cause neurodegenerative diseases.",
      "The blood-brain barrier protects the brain from pathogens.",
      "Neurons communicate via synapses using neurotransmitters.",
      "Neuroplasticity allows the brain to reorganize throughout life.",
      "REM sleep is when most dreaming occurs.",
      "Circadian rhythms regulate sleep-wake cycles.",
      "The placebo effect demonstrates mind-body connection.",
      "Evolution occurs through natural selection acting on genetic variation.",
      "Convergent evolution produces similar traits in unrelated species.",
      "Mass extinctions have occurred five times in Earth's history.",
      "The Cambrian Explosion saw rapid diversification of life 541 million years ago.",
      "Dinosaurs went extinct 66 million years ago, likely from an asteroid impact.",
      "Birds are direct descendants of theropod dinosaurs.",
      "The endosymbiotic theory explains the origin of mitochondria and chloroplasts.",
      "Radiometric dating uses radioactive decay to determine age of rocks.",
      "Continental drift theory states continents slowly move across Earth's surface.",
      "Seafloor spreading creates new oceanic crust at mid-ocean ridges.",
      "The Wilson Cycle describes the opening and closing of ocean basins.",
    ],
    Hard: [
      "The Standard Model of particle physics includes 17 fundamental particles.",
      "Quarks come in six flavors: up, down, strange, charm, bottom, top.",
      "The Higgs boson gives mass to elementary particles through the Higgs field.",
      "Supersymmetry predicts every particle has a superpartner.",
      "String theory proposes fundamental particles are one-dimensional strings.",
      "M-theory unifies five string theory variants in 11 dimensions.",
      "The holographic principle suggests 3D space is encoded on a 2D surface.",
      "Loop quantum gravity quantizes spacetime into discrete units.",
      "The many-worlds interpretation posits parallel universes for quantum outcomes.",
      "Decoherence explains the quantum-to-classical transition.",
      "The measurement problem questions what constitutes quantum measurement.",
      "Bell's theorem proves local hidden variables cannot explain quantum correlations.",
      "Quantum tunneling allows particles to pass through energy barriers.",
      "The Casimir effect creates force between uncharged metal plates in vacuum.",
      "Topological quantum computing uses anyons for error-resistant qubits.",
      "The cosmological constant problem questions dark energy's value.",
      "Inflation theory explains the universe's homogeneity and flatness.",
      "The anthropic principle relates universe's properties to observer existence.",
      "The Fermi paradox questions why we haven't detected alien civilizations.",
      "The Drake equation estimates the number of communicative civilizations.",
      "The Great Filter hypothesis suggests barriers to interstellar civilizations.",
      "Panspermia proposes life spreads between planets via meteorites.",
      "The RNA world hypothesis suggests RNA preceded DNA in early life.",
      "Horizontal gene transfer allows bacteria to share genes across species.",
      "The neutral theory of evolution emphasizes genetic drift over selection.",
      "Punctuated equilibrium suggests evolution occurs in rapid bursts.",
      "Evo-devo examines how developmental processes affect evolution.",
      "The Modern Synthesis integrated Mendelian genetics with Darwinian evolution.",
      "Adaptive radiation explains rapid species diversification.",
      "Allopatric speciation occurs when populations are geographically separated.",
      "The Red Queen hypothesis states species must constantly adapt to survive.",
      "Kin selection explains altruistic behavior toward relatives.",
      "Game theory models evolutionary stable strategies.",
      "The Baldwin effect describes how learning influences evolution.",
      "Epigenetic inheritance can transmit acquired characteristics.",
      "Telomerase extends telomeres and is active in cancer cells.",
      "Apoptosis is programmed cell death essential for development.",
      "Autophagy recycles cellular components during stress.",
      "The Warburg effect describes cancer cells' preference for glycolysis.",
      "Immunotherapy harnesses the immune system to fight cancer.",
      "CAR-T cell therapy engineers T cells to target cancer.",
      "Optogenetics uses light to control neurons expressing photosensitive proteins.",
      "Brain-computer interfaces decode neural signals for external control.",
      "The connectome maps all neural connections in the brain.",
      "Default mode network activates during rest and self-referential thinking.",
      "Neurogenesis continues in adult hippocampus.",
      "Long-term potentiation strengthens synapses for memory formation.",
      "The glymphatic system clears waste from the brain during sleep.",
      "Mirror neurons activate both during action and observation.",
      "The global workspace theory explains consciousness as information integration.",
      "Integrated information theory quantifies consciousness with phi.",
    ]
  },

  'History': {
    Easy: [
      "World War I lasted from 1914 to 1918.",
      "World War II ended in 1945.",
      "The American Civil War was fought from 1861 to 1865.",
      "Christopher Columbus reached the Americas in 1492.",
      "The Declaration of Independence was signed in 1776.",
      "The French Revolution began in 1789.",
      "The Berlin Wall fell in 1989.",
      "The Titanic sank on April 15, 1912.",
      "Julius Caesar was assassinated in 44 BCE.",
      "The Roman Empire fell in 476 CE.",
      "The Renaissance began in Italy in the 14th century.",
      "The Industrial Revolution started in Britain in the late 1700s.",
      "The printing press was invented by Johannes Gutenberg around 1440.",
      "Martin Luther posted his 95 Theses in 1517, starting the Reformation.",
      "The Magna Carta was signed in 1215.",
      "The Black Death killed millions in Europe in the 1340s-1350s.",
      "The American Revolutionary War lasted from 1775 to 1783.",
      "Napoleon Bonaparte was defeated at Waterloo in 1815.",
      "The Louisiana Purchase occurred in 1803.",
      "The Treaty of Versailles ended World War I in 1919.",
      "The United Nations was founded in 1945.",
      "The Cold War lasted from roughly 1947 to 1991.",
      "The Korean War lasted from 1950 to 1953.",
      "The Vietnam War ended in 1975.",
      "The Cuban Missile Crisis occurred in October 1962.",
      "Man first landed on the Moon in 1969.",
      "The Soviet Union dissolved in 1991.",
      "Nelson Mandela was released from prison in 1990.",
      "The European Union was established in 1993.",
      "The September 11 attacks occurred in 2001.",
      "The Great Depression began with the stock market crash of 1929.",
      "Pearl Harbor was attacked on December 7, 1941.",
      "D-Day occurred on June 6, 1944.",
      "The atomic bombs were dropped on Japan in August 1945.",
      "The Holocaust killed approximately 6 million Jews.",
      "Gandhi led India to independence from Britain in 1947.",
      "The Suez Crisis occurred in 1956.",
      "The Space Race began in the 1950s.",
      "The first Earth Day was celebrated in 1970.",
      "The personal computer revolution began in the 1970s-1980s.",
      "The internet became publicly accessible in the 1990s.",
      "The Human Genome Project was completed in 2003.",
      "Barack Obama became the first African American president in 2009.",
      "The Arab Spring uprisings occurred in 2010-2011.",
      "Brexit occurred in 2020.",
      "The COVID-19 pandemic began in 2019-2020.",
      "Ancient Egypt's pyramids were built around 2500 BCE.",
      "The Great Wall of China was built over many centuries.",
      "Alexander the Great died in 323 BCE.",
      "The Byzantine Empire lasted until 1453.",
    ],
    Medium: [
      "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.",
      "The shortest war in history lasted 38 minutes between Britain and Zanzibar in 1896.",
      "Oxford University is older than the Aztec Empire.",
      "The Great Fire of London in 1666 helped end the Great Plague outbreak.",
      "Ada Lovelace is considered the first computer programmer in the 1840s.",
      "The Treaty of Westphalia in 1648 established modern state sovereignty.",
      "The Code of Hammurabi from 1750 BCE is one of the oldest legal codes.",
      "The Library of Alexandria was destroyed multiple times over several centuries.",
      "Genghis Khan's empire was the largest contiguous land empire in history.",
      "The Silk Road connected Asia and Europe for over 1,500 years.",
      "The Vikings reached North America around 1000 CE, before Columbus.",
      "The Spanish Flu of 1918-1919 killed more people than World War I.",
      "The Mongol Empire killed an estimated 40 million people, reducing global population.",
      "The Pax Romana was a 200-year period of relative peace in the Roman Empire.",
      "The Byzantine Empire preserved Greek and Roman knowledge through the Middle Ages.",
      "The Ottoman Empire lasted over 600 years from 1299 to 1922.",
      "The Ming Dynasty built most of the current Great Wall of China.",
      "The Inca Empire had no written language but used quipu for record-keeping.",
      "The Mali Empire's Mansa Musa was possibly the richest person in history.",
      "The Hundred Years' War actually lasted 116 years from 1337 to 1453.",
      "Joan of Arc was burned at the stake at age 19 in 1431.",
      "The Spanish Inquisition lasted from 1478 to 1834.",
      "The Gutenberg Bible was the first major book printed with movable type.",
      "The Protestant Reformation split Western Christianity.",
      "The Scientific Revolution transformed understanding of the natural world.",
      "The Enlightenment emphasized reason and individual rights.",
      "The Seven Years' War (1756-1763) was a global conflict.",
      "The Boston Tea Party occurred in 1773 as protest against British taxes.",
      "The Bastille was stormed on July 14, 1789, a symbol of the French Revolution.",
      "Napoleon crowned himself Emperor of France in 1804.",
      "The Congress of Vienna in 1815 redrew Europe's map.",
      "The Monroe Doctrine of 1823 opposed European colonialism in the Americas.",
      "The Opium Wars opened China to Western trade in the 19th century.",
      "The Meiji Restoration modernized Japan in 1868.",
      "The Scramble for Africa saw European powers colonize most of Africa by 1914.",
      "The Boer Wars were fought between Britain and Dutch settlers in South Africa.",
      "The Russian Revolution of 1917 overthrew the Tsar and established Soviet power.",
      "The Weimar Republic struggled in Germany between World Wars.",
      "The Long March of 1934-1935 saved the Chinese Communist Party.",
      "The Manhattan Project developed the atomic bomb during WWII.",
      "The Marshall Plan helped rebuild Western Europe after WWII.",
      "The Berlin Airlift of 1948-1949 supplied West Berlin during Soviet blockade.",
      "The McCarthy era saw anti-communist witch hunts in 1950s America.",
      "The Civil Rights Movement peaked in the 1960s in the United States.",
      "The Six-Day War of 1967 reshaped the Middle East.",
      "The Prague Spring of 1968 was crushed by Soviet invasion.",
      "The Watergate scandal led to Nixon's resignation in 1974.",
      "The Iranian Revolution of 1979 established an Islamic Republic.",
      "The fall of the Soviet Union marked the end of the Cold War.",
      "The Rwandan genocide killed 800,000 people in 100 days in 1994.",
    ],
    Hard: [
      "The Peace of Augsburg in 1555 established cuius regio, eius religio.",
      "The Defenestration of Prague in 1618 sparked the Thirty Years' War.",
      "The Treaty of Utrecht in 1713 ended the War of Spanish Succession.",
      "The Glorious Revolution of 1688 established parliamentary sovereignty in England.",
      "The Edict of Nantes granted religious tolerance in France until revoked in 1685.",
      "The Diet of Worms in 1521 condemned Martin Luther as a heretic.",
      "The Council of Trent (1545-1563) was the Catholic Church's response to Reformation.",
      "The Congress of Berlin in 1878 reorganized Balkan states after Russo-Turkish War.",
      "The Sykes-Picot Agreement of 1916 secretly divided the Ottoman Empire.",
      "The Zimmermann Telegram helped bring the US into World War I.",
      "The Kellogg-Briand Pact of 1928 attempted to outlaw war.",
      "The Molotov-Ribbentrop Pact was a Nazi-Soviet non-aggression treaty in 1939.",
      "The Atlantic Charter of 1941 outlined Allied goals for post-war world.",
      "The Yalta Conference in 1945 divided post-war spheres of influence.",
      "The Truman Doctrine of 1947 committed the US to containing communism.",
      "The Warsaw Pact was formed in 1955 as Soviet response to NATO.",
      "The Bandung Conference of 1955 launched the Non-Aligned Movement.",
      "The Sino-Soviet split in the 1960s divided the communist world.",
      "The Helsinki Accords of 1975 improved East-West relations.",
      "The Camp David Accords of 1978 achieved Egyptian-Israeli peace.",
      "The Gdansk Agreement of 1980 led to Solidarity union in Poland.",
      "The Tiananmen Square protests of 1989 were violently suppressed.",
      "The Maastricht Treaty of 1992 created the European Union.",
      "The Good Friday Agreement of 1998 brought peace to Northern Ireland.",
      "The Dayton Accords ended the Bosnian War in 1995.",
      "The Treaty of Versailles created the League of Nations.",
      "The Kellogg-Briand Pact of 1928 renounced war as policy.",
      "The Munich Agreement of 1938 appeased Hitler by ceding Sudetenland.",
      "The Potsdam Conference determined post-WWII Germany's fate.",
      "The Marshall Plan provided $13 billion to rebuild Europe.",
      "The Berlin Blockade tested Western resolve in 1948-49.",
      "The Korean War established the 38th parallel division.",
      "The Suez Crisis of 1956 marked the decline of European imperial power.",
      "The Bay of Pigs invasion failed to overthrow Castro in 1961.",
      "The Gulf of Tonkin incident escalated US involvement in Vietnam.",
      "The Tet Offensive of 1968 turned US public opinion against Vietnam War.",
      "The Paris Peace Accords ended US involvement in Vietnam in 1973.",
      "The Camp David Accords normalized Egyptian-Israeli relations.",
      "The Iranian hostage crisis lasted 444 days from 1979-1981.",
      "The Soviet-Afghan War lasted from 1979 to 1989.",
      "The Falklands War was fought between Britain and Argentina in 1982.",
      "The First Intifada began in 1987 in Palestinian territories.",
      "The Velvet Revolution peacefully ended communism in Czechoslovakia in 1989.",
      "The reunification of Germany occurred on October 3, 1990.",
      "The First Gulf War liberated Kuwait from Iraq in 1991.",
      "The Bosnian War saw ethnic cleansing from 1992-1995.",
      "The Oslo Accords attempted Israeli-Palestinian peace in 1993.",
      "The Rwandan genocide occurred in 1994.",
      "The Kosovo War led to NATO intervention in 1999.",
      "The September 11 attacks triggered the War on Terror.",
      "The Iraq War began in 2003 based on disputed WMD claims.",
    ]
  },

  'Sports': {
    Easy: [
      "The FIFA World Cup is held every four years.",
      "The Olympics occur every four years (Summer and Winter alternate every two years).",
      "A soccer match has two halves of 45 minutes each.",
      "Basketball was invented by James Naismith in 1891.",
      "Baseball has nine innings in a standard game.",
      "American football has four quarters of 15 minutes each.",
      "Tennis scoring goes 15, 30, 40, game.",
      "A golf course typically has 18 holes.",
      "Boxing matches are divided into rounds.",
      "Formula 1 is the highest class of international auto racing.",
      "The Tour de France is cycling's most prestigious race.",
      "Wimbledon is the oldest tennis tournament, started in 1877.",
      "Michael Jordan played for the Chicago Bulls.",
      "Usain Bolt holds the 100m world record at 9.58 seconds.",
      "Michael Phelps has won 23 Olympic gold medals.",
      "Serena Williams has won 23 Grand Slam singles titles.",
      "Lionel Messi has won seven Ballon d'Or awards.",
      "Cristiano Ronaldo has scored over 800 career goals.",
      "Tom Brady won seven Super Bowl championships.",
      "Tiger Woods has won 15 major golf championships.",
      "Muhammad Ali was a three-time heavyweight boxing champion.",
      "Pelé scored over 1,000 career goals.",
      "Diego Maradona's 'Hand of God' goal occurred in 1986.",
      "Jesse Owens won four gold medals at the 1936 Olympics.",
      "Babe Ruth hit 714 career home runs.",
      "Wayne Gretzky is hockey's all-time leading scorer.",
      "Roger Federer has won 20 Grand Slam titles.",
      "LeBron James has won four NBA championships.",
      "The Boston Celtics have won 17 NBA championships.",
      "The New York Yankees have won 27 World Series titles.",
      "Brazil has won five FIFA World Cups.",
      "The Premier League is England's top football division.",
      "The Super Bowl is the NFL's championship game.",
      "The Stanley Cup is hockey's championship trophy.",
      "The Masters is golf's first major of the year.",
      "The Kentucky Derby is horse racing's most famous race.",
      "Marathon distance is 26.2 miles or 42.195 kilometers.",
      "A triathlon consists of swimming, cycling, and running.",
      "The decathlon consists of ten track and field events.",
      "Cricket is played with 11 players per side.",
      "Rugby has two main variants: union and league.",
      "MMA stands for Mixed Martial Arts.",
      "NASCAR races are primarily held on oval tracks.",
      "The Daytona 500 is NASCAR's biggest race.",
      "The Indy 500 is held at Indianapolis Motor Speedway.",
      "Volleyball was invented in 1895 by William G. Morgan.",
      "Table tennis originated in England in the 1880s.",
      "Badminton can have shuttlecocks reach speeds over 200 mph.",
      "Fencing has three disciplines: foil, épée, and sabre.",
      "Gymnastics includes artistic, rhythmic, and trampoline disciplines.",
    ],
    Medium: [
      "The four tennis Grand Slams are Australian Open, French Open, Wimbledon, and US Open.",
      "Golf's four majors are The Masters, PGA Championship, US Open, and The Open Championship.",
      "The Triple Crown in horse racing consists of Kentucky Derby, Preakness, and Belmont Stakes.",
      "Soccer's golden goal rule was used from 1993 to 2004.",
      "The Heisman Trophy is awarded to college football's best player.",
      "The FIFA World Cup trophy is made of 18-karat gold.",
      "Olympic gold medals are actually silver coated with gold.",
      "The Boston Marathon is the world's oldest annual marathon (since 1897).",
      "The first modern Olympics were held in Athens in 1896.",
      "Women were first allowed in the Olympics in 1900.",
      "The Olympic torch relay started at the 1936 Berlin Olympics.",
      "Basketball was added to the Olympics in 1936.",
      "The three-point line in basketball was adopted by the NBA in 1979.",
      "The shot clock in basketball was introduced in 1954.",
      "Baseball's designated hitter rule started in the AL in 1973.",
      "The NFL-AFL merger occurred in 1970.",
      "The Super Bowl era began in 1967.",
      "Monday Night Football debuted in 1970.",
      "The forward pass was legalized in football in 1906.",
      "Hockey's Original Six era was from 1942 to 1967.",
      "The NHL expanded from six to twelve teams in 1967.",
      "The World Hockey Association competed with the NHL from 1972-1979.",
      "Soccer's offside rule was modified in 1990 to give attackers advantage.",
      "The back-pass rule in soccer was introduced in 1992.",
      "VAR (Video Assistant Referee) was introduced in soccer in 2018.",
      "Cricket's Twenty20 format was created in 2003.",
      "Test cricket matches can last up to five days.",
      "Rugby union became professional in 1995.",
      "The Rugby World Cup started in 1987.",
      "The Six Nations Championship is rugby union's oldest tournament.",
      "Formula 1 World Championship started in 1950.",
      "F1 cars can accelerate from 0-100 mph in under 2 seconds.",
      "NASCAR uses restrictor plates at superspeedways for safety.",
      "The Indianapolis 500 has been held annually since 1911 (except war years).",
      "Le Mans 24 Hours is the world's oldest active endurance race.",
      "The Tour de France was first held in 1903.",
      "The Giro d'Italia is cycling's second most prestigious race.",
      "Track cycling was part of the first modern Olympics.",
      "BMX racing became an Olympic sport in 2008.",
      "Skateboarding debuted at the 2020 Olympics.",
      "Surfing also debuted at the 2020 Olympics.",
      "Sport climbing was added to the Olympics in 2020.",
      "Breaking (breakdancing) will debut at the 2024 Olympics.",
      "The modern pentathlon consists of fencing, swimming, equestrian, running, and shooting.",
      "The decathlon includes 100m, long jump, shot put, high jump, 400m, 110m hurdles, discus, pole vault, javelin, and 1500m.",
      "The heptathlon is the women's equivalent with seven events.",
      "Pole vaulters can clear heights over 6 meters (20 feet).",
      "High jumpers use the Fosbury Flop technique.",
      "Discus throw has origins in ancient Greece.",
      "The hammer throw uses a 16-pound ball on a wire.",
    ],
    Hard: [
      "The Miracle on Ice occurred when the US beat USSR in hockey at the 1980 Olympics.",
      "Don Larsen pitched the only perfect game in World Series history in 1956.",
      "Wilt Chamberlain scored 100 points in a single NBA game in 1962.",
      "The Thrilla in Manila between Ali and Frazier occurred in 1975.",
      "The Rumble in the Jungle saw Ali defeat Foreman in 1974.",
      "Bobby Fischer defeated Boris Spassky in the 1972 World Chess Championship.",
      "Secretariat won the Triple Crown by 31 lengths in the Belmont Stakes.",
      "The 1972 Munich Olympics were marred by a terrorist attack.",
      "The Black Sox scandal involved fixing the 1919 World Series.",
      "Jackie Robinson broke baseball's color barrier in 1947.",
      "The Shot Heard 'Round the World was Bobby Thomson's 1951 home run.",
      "Roger Bannister first broke the four-minute mile in 1954.",
      "Bob Beamon's long jump record stood for 23 years from 1968.",
      "The Fosbury Flop revolutionized high jumping at the 1968 Olympics.",
      "Dick Fosbury won gold using his unconventional technique.",
      "The 1980 Olympics boycott involved 65 nations over Soviet invasion of Afghanistan.",
      "The 1984 Olympics saw a Soviet-led boycott in response.",
      "Ben Johnson's 1988 Olympic gold was stripped for doping.",
      "The BALCO scandal exposed systematic doping in the 2000s.",
      "Lance Armstrong was stripped of seven Tour de France titles for doping.",
      "The Russia doping scandal led to Olympic bans in 2016 and 2020.",
      "Calciopoli scandal involved match-fixing in Italian soccer in 2006.",
      "The Bosman ruling in 1995 changed European soccer's transfer system.",
      "The Taylor Report mandated all-seater stadiums after Hillsborough disaster.",
      "The Heysel Stadium disaster in 1985 led to English clubs' European ban.",
      "The Bradford City stadium fire killed 56 people in 1985.",
      "The Munich air disaster killed eight Manchester United players in 1958.",
      "The Superga air disaster killed the entire Torino team in 1949.",
      "The Chapecoense plane crash killed most of the team in 2016.",
      "The Hand of God goal was scored by Maradona against England in 1986.",
      "Geoff Hurst's controversial goal in 1966 World Cup final remains debated.",
      "Zinedine Zidane was sent off in the 2006 World Cup final for headbutting.",
      "Luis Suárez's handball prevented Ghana from reaching 2010 World Cup semifinals.",
      "The Battle of Santiago in 1962 was one of soccer's most violent matches.",
      "The Disgrace of Gijón saw West Germany and Austria both advance in 1982.",
      "The Miracle of Istanbul saw Liverpool overcome 3-0 deficit to win 2005 Champions League.",
      "Manchester United's treble in 1999 was won with a dramatic Champions League final.",
      "Leicester City won the Premier League at 5000-1 odds in 2016.",
      "The Greek national team won Euro 2004 as 150-1 outsiders.",
      "Denmark won Euro 1992 despite not qualifying initially.",
      "The Immaculate Reception is NFL's most famous play from 1972.",
      "The Music City Miracle was a controversial lateral play in 2000.",
      "The Tuck Rule game in 2002 changed the Patriots' dynasty trajectory.",
      "The New York Giants' helmet catch helped defeat undefeated Patriots in Super Bowl XLII.",
      "The Philly Special trick play won Super Bowl LII for the Eagles.",
      "The Minneapolis Miracle was a last-second touchdown in 2018 playoffs.",
      "Michael Jordan's flu game in 1997 NBA Finals is legendary.",
      "Magic Johnson's Game 6 performance as rookie center in 1980 Finals.",
      "Larry Bird and Magic Johnson's rivalry revitalized the NBA in the 1980s.",
      "The Malice at the Palace brawl in 2004 led to severe NBA suspensions.",
    ]
  },

  'Pop Culture': {
    Easy: [
      "The Beatles formed in Liverpool in 1960.",
      "Elvis Presley is known as the King of Rock and Roll.",
      "Michael Jackson is called the King of Pop.",
      "Madonna is known as the Queen of Pop.",
      "Star Wars was released in 1977.",
      "The Simpsons premiered in 1989.",
      "Friends ran from 1994 to 2004.",
      "Game of Thrones premiered in 2011.",
      "Harry Potter books were written by J.K. Rowling.",
      "The first Harry Potter book was published in 1997.",
      "Pokémon was created in Japan in 1996.",
      "Super Mario Bros. was released in 1985.",
      "Netflix started as a DVD rental service in 1997.",
      "YouTube was founded in 2005.",
      "TikTok launched internationally in 2017.",
      "Spotify was founded in 2006.",
      "Apple's iPod was released in 2001.",
      "The iPhone was announced in 2007.",
      "Facebook was founded in 2004.",
      "Instagram launched in 2010.",
      "Twitter was created in 2006.",
      "Snapchat launched in 2011.",
      "Marvel Cinematic Universe began with Iron Man in 2008.",
      "Avatar became the highest-grossing film in 2009.",
      "Titanic held the box office record from 1997 to 2009.",
      "Disney was founded in 1923 by Walt Disney.",
      "Pixar's first feature film was Toy Story in 1995.",
      "The Lion King was released in 1994.",
      "Frozen became a cultural phenomenon in 2013.",
      "Taylor Swift released her first album in 2006.",
      "Beyoncé was part of Destiny's Child before going solo.",
      "Adele's 21 is one of the best-selling albums of all time.",
      "BTS became global K-pop phenomenon in the 2010s.",
      "Billie Eilish won five Grammys in 2020 at age 18.",
      "The Super Bowl halftime show is one of TV's most-watched events.",
      "The Oscars (Academy Awards) started in 1929.",
      "The Grammy Awards began in 1959.",
      "The Emmy Awards honor television excellence.",
      "The Tony Awards celebrate Broadway theater.",
      "Comic-Con started in San Diego in 1970.",
      "Coachella music festival began in 1999.",
      "Glastonbury Festival started in 1970.",
      "Woodstock music festival occurred in 1969.",
      "Live Aid concerts raised money for famine relief in 1985.",
      "MTV launched in 1981 with 'Video Killed the Radio Star'.",
      "Reality TV exploded with Survivor in 2000.",
      "American Idol premiered in 2002.",
      "The Voice started in 2011.",
      "Black Mirror premiered in 2011.",
      "Stranger Things premiered on Netflix in 2016.",
    ],
    Medium: [
      "The Beatles appeared on The Ed Sullivan Show in 1964, watched by 73 million.",
      "Woodstock attracted 400,000 people to a farm in New York.",
      "Elvis Presley's first TV appearance caused controversy for his hip movements.",
      "Michael Jackson's Thriller is the best-selling album of all time.",
      "The moonwalk was popularized by Michael Jackson in 1983.",
      "Prince changed his name to an unpronounceable symbol in 1993.",
      "Nirvana's Nevermind helped popularize grunge music in 1991.",
      "The 27 Club refers to famous musicians who died at age 27.",
      "Tupac and Biggie's deaths in the 1990s shocked hip-hop.",
      "The first music video on MTV was The Buggles' 'Video Killed the Radio Star'.",
      "Thriller's music video revolutionized the music video format.",
      "Live Aid was broadcast to 1.9 billion people in 1985.",
      "We Are the World raised money for famine relief in 1985.",
      "The first Academy Awards ceremony lasted 15 minutes in 1929.",
      "The Godfather won Best Picture in 1973.",
      "Citizen Kane is often called the greatest film ever made.",
      "Gone with the Wind held the inflation-adjusted box office record for decades.",
      "Jaws is credited with creating the summer blockbuster in 1975.",
      "E.T. was the highest-grossing film of the 1980s.",
      "Jurassic Park revolutionized CGI in 1993.",
      "The Blair Witch Project pioneered found footage horror in 1999.",
      "Paranormal Activity was made for $15,000 and grossed $193 million.",
      "The Lord of the Rings trilogy won 17 Oscars total.",
      "Return of the King won all 11 Oscars it was nominated for.",
      "Disney Renaissance refers to 1989-1999 animated classics.",
      "Shrek revolutionized computer-animated features in 2001.",
      "Toy Story was the first fully computer-animated feature film.",
      "The Simpsons is the longest-running American sitcom.",
      "South Park has been running since 1997.",
      "Family Guy was cancelled then revived due to DVD sales.",
      "Breaking Bad is considered one of TV's greatest dramas.",
      "The Sopranos pioneered prestige TV drama in 1999.",
      "The Wire is acclaimed for its realistic portrayal of Baltimore.",
      "Lost's finale was watched by 13.5 million viewers.",
      "Seinfeld's finale drew 76 million viewers in 1998.",
      "M*A*S*H's finale in 1983 was watched by 125 million.",
      "I Love Lucy pioneered the three-camera sitcom format.",
      "Star Trek inspired a devoted fanbase despite low ratings.",
      "Doctor Who has been running since 1963 (with a gap).",
      "The Twilight Zone anthology series ran from 1959-1964.",
      "Saturday Night Live has launched many comedy careers since 1975.",
      "Oprah Winfrey's talk show ran for 25 years.",
      "The Tonight Show has been running since 1954.",
      "Jeopardy! has been hosted by Alex Trebek from 1984-2020.",
      "Wheel of Fortune has been running since 1975.",
      "Sesame Street revolutionized children's television in 1969.",
      "Mister Rogers' Neighborhood ran from 1968 to 2001.",
      "Bob Ross's The Joy of Painting became a cultural phenomenon.",
      "The first Super Bowl halftime show with major acts was in 1993.",
      "Janet Jackson's wardrobe malfunction occurred at Super Bowl XXXVIII.",
    ],
    Hard: [
      "The Velvet Underground's first album sold poorly but everyone who bought it started a band.",
      "Brian Eno produced U2's most acclaimed albums in the 1980s and 1990s.",
      "The Stooges' Raw Power is considered a proto-punk masterpiece.",
      "My Bloody Loveless pioneered the shoegaze genre in 1991.",
      "Radiohead's OK Computer is considered one of rock's greatest albums.",
      "Kanye West's My Beautiful Dark Twisted Fantasy redefined hip-hop production.",
      "Pet Sounds by the Beach Boys influenced the Beatles' Sgt. Pepper's.",
      "The Velvet Underground & Nico's banana cover was designed by Andy Warhol.",
      "Laurel Canyon was the epicenter of 1960s California rock.",
      "The Brill Building in New York produced numerous hit songs in the 1960s.",
      "Motown's Funk Brothers played on more #1 hits than Elvis, Beatles, Stones combined.",
      "Phil Spector's Wall of Sound production technique defined 1960s pop.",
      "The 'British Invasion' began with the Beatles in 1964.",
      "Punk rock emerged from CBGB club in New York in the mid-1970s.",
      "Hip-hop originated at 1520 Sedgwick Avenue in the Bronx in 1973.",
      "Graffiti art emerged from New York subway culture.",
      "Breakdancing developed as part of hip-hop culture in the 1970s.",
      "DJing and turntablism became recognized art forms.",
      "Sampling transformed music production but raised copyright issues.",
      "Auto-Tune was released in 1997 and changed pop music.",
      "Napster disrupted the music industry from 1999-2001.",
      "iTunes launched in 2001, revolutionizing music distribution.",
      "Spotify's streaming model changed how artists earn money.",
      "Citizen Kane used innovative deep focus cinematography.",
      "The French New Wave revolutionized cinema in the late 1950s.",
      "Italian Neorealism influenced post-war cinema.",
      "The Hays Code censored Hollywood films from 1934-1968.",
      "Method acting was popularized by the Actors Studio.",
      "The Stanislavski system influenced modern acting techniques.",
      "Film noir emerged in 1940s Hollywood.",
      "Blaxploitation films emerged in the 1970s.",
      "New Hollywood movement started in the late 1960s.",
      "Blockbuster era began with Jaws and Star Wars.",
      "The Muppet Show ran from 1976-1981 and reached 235 million viewers.",
      "Mystery Science Theater 3000 pioneered ironic TV commentary.",
      "Twin Peaks revolutionized TV drama in 1990.",
      "The X-Files popularized alien conspiracy mythology.",
      "Buffy the Vampire Slayer subverted horror and teen drama tropes.",
      "The West Wing portrayed an idealistic presidency from 1999-2006.",
      "24's real-time format was innovative in 2001.",
      "Lost pioneered complex narrative and online fan communities.",
      "The Marvel Cinematic Universe created interconnected storytelling.",
      "Quentin Tarantino's nonlinear narratives influenced 1990s cinema.",
      "Christopher Nolan's complex narratives challenged audiences.",
      "A24 films defined 2010s independent cinema aesthetic.",
      "Streaming services changed how TV shows are produced and watched.",
      "Binge-watching became cultural phenomenon with Netflix.",
      "Peak TV refers to the explosion of quality content in the 2010s.",
      "Prestige TV elevated television to rival cinema in quality.",
      "Social media changed how celebrities interact with fans.",
      "Viral marketing campaigns became essential for entertainment.",
    ]
  },

  'Crypto/Web3': {
    Easy: [
      "Bitcoin was created in 2009 by Satoshi Nakamoto.",
      "Bitcoin's maximum supply is capped at 21 million coins.",
      "Ethereum was proposed by Vitalik Buterin in 2013.",
      "Blockchain is a distributed ledger technology.",
      "Cryptocurrency uses cryptography for security.",
      "Mining is the process of validating blockchain transactions.",
      "A wallet stores your cryptocurrency private keys.",
      "Public and private keys enable cryptocurrency transactions.",
      "Bitcoin halving occurs approximately every four years.",
      "Satoshi is the smallest unit of Bitcoin (0.00000001 BTC).",
      "Smart contracts are self-executing agreements on blockchain.",
      "DeFi stands for Decentralized Finance.",
      "NFT stands for Non-Fungible Token.",
      "Gas fees are transaction costs on Ethereum.",
      "Proof of Work requires computational power to mine blocks.",
      "Proof of Stake validates transactions through staking.",
      "HODL originated from a misspelled 'hold' in a Bitcoin forum.",
      "Altcoins refer to cryptocurrencies other than Bitcoin.",
      "Stablecoins are pegged to stable assets like the US dollar.",
      "Decentralization means no single entity controls the network.",
      "Consensus mechanisms ensure network agreement on transactions.",
      "Hash functions create unique fingerprints of data.",
      "Nodes are computers that maintain the blockchain network.",
      "Forks create new versions of blockchain protocols.",
      "Cold storage keeps cryptocurrency offline for security.",
      "Hot wallets are connected to the internet.",
      "Exchange platforms allow cryptocurrency trading.",
      "Liquidity refers to how easily assets can be bought/sold.",
      "Market cap is calculated by price times circulating supply.",
      "Bull market means prices are rising.",
      "Bear market means prices are falling.",
      "Volatility refers to price fluctuations.",
      "FOMO means Fear Of Missing Out on gains.",
      "FUD stands for Fear, Uncertainty, and Doubt.",
      "Pump and dump schemes artificially inflate prices.",
      "Rug pull is when developers abandon a project with investors' money.",
      "Whales are individuals or entities holding large amounts of cryptocurrency.",
      "Sharding divides blockchain into smaller pieces for scalability.",
      "Layer 2 solutions improve blockchain scalability.",
      "Cross-chain technology enables interaction between different blockchains.",
      "Oracles provide external data to smart contracts.",
      "DAO stands for Decentralized Autonomous Organization.",
      "Tokenomics studies the economics of cryptocurrency tokens.",
      "Burning tokens permanently removes them from circulation.",
      "Airdrop distributes free tokens to wallet addresses.",
      "ICO stands for Initial Coin Offering.",
      "White paper describes a cryptocurrency project's technical details.",
      "KYC means Know Your Customer verification.",
      "AML stands for Anti-Money Laundering regulations.",
      "Peer-to-peer transactions occur directly between users.",
    ],
    Medium: [
      "The first Bitcoin transaction was for two pizzas worth 10,000 BTC in 2010.",
      "Bitcoin's genesis block contains the text 'Chancellor on brink of second bailout for banks'.",
      "Ethereum transitioned from Proof of Work to Proof of Stake in 2022 (The Merge).",
      "Ethereum's DAO hack in 2016 led to a controversial hard fork.",
      "The Bitcoin halving reduces mining rewards by 50%.",
      "Litecoin was created by Charlie Lee in 2011 as 'silver to Bitcoin's gold'.",
      "Ripple (XRP) focuses on enabling fast international payments.",
      "Cardano uses a research-driven approach to blockchain development.",
      "Solana emphasizes high transaction throughput and low fees.",
      "Polkadot enables interoperability between different blockchains.",
      "Avalanche uses a unique consensus mechanism for speed.",
      "Cosmos calls itself the 'internet of blockchains'.",
      "Binance Smart Chain offers lower fees than Ethereum.",
      "Uniswap pioneered automated market maker (AMM) DEXs.",
      "Compound Finance enabled decentralized lending and borrowing.",
      "Aave is a leading DeFi lending protocol.",
      "MakerDAO's DAI is an algorithmic stablecoin.",
      "Chainlink provides decentralized oracle services.",
      "The Graph indexes blockchain data for easy querying.",
      "Polygon (formerly Matic) is an Ethereum scaling solution.",
      "Arbitrum and Optimism are Ethereum layer 2 rollups.",
      "Lightning Network enables fast Bitcoin transactions.",
      "Wrapped Bitcoin (WBTC) brings Bitcoin to Ethereum.",
      "Yield farming involves staking crypto to earn rewards.",
      "Liquidity mining rewards users for providing liquidity.",
      "Impermanent loss affects liquidity providers in AMMs.",
      "Flash loans allow uncollateralized borrowing within one transaction.",
      "MEV (Maximal Extractable Value) can be extracted by miners/validators.",
      "Slippage occurs when prices change during large trades.",
      "Sandwich attacks exploit transaction ordering.",
      "Front-running involves placing transactions ahead of pending ones.",
      "Reentrancy attacks exploit contract vulnerabilities.",
      "ERC-20 is the standard for fungible tokens on Ethereum.",
      "ERC-721 is the standard for NFTs on Ethereum.",
      "ERC-1155 allows both fungible and non-fungible tokens.",
      "Gas optimization reduces transaction costs on Ethereum.",
      "Merkle trees verify data integrity efficiently.",
      "Zero-knowledge proofs enable privacy-preserving transactions.",
      "zk-SNARKs are used in privacy coins like Zcash.",
      "Ring signatures provide anonymity in Monero.",
      "CoinJoin mixes transactions for privacy.",
      "Taproot upgrade improved Bitcoin privacy and efficiency.",
      "SegWit increased Bitcoin's transaction capacity.",
      "Bitcoin's difficulty adjusts every 2,016 blocks.",
      "51% attacks require controlling majority of network hash power.",
      "Double-spending is prevented by blockchain consensus.",
      "Timestamping proves data existed at specific time.",
      "Immutability means blockchain records cannot be altered.",
    ],
    Hard: [
      "Byzantine Fault Tolerance ensures consensus despite malicious actors.",
      "Practical Byzantine Fault Tolerance (PBFT) handles up to 1/3 malicious nodes.",
      "Nakamoto consensus combines Proof of Work with longest chain rule.",
      "Ethereum's Casper implements Proof of Stake with finality.",
      "Tendermint consensus provides instant finality.",
      "Delegated Proof of Stake (DPoS) uses elected validators.",
      "Proof of Authority relies on approved validators.",
      "Avalanche consensus uses metastability for agreement.",
      "DAG (Directed Acyclic Graph) structures like IOTA avoid traditional blockchain.",
      "Sharding divides state across multiple chains for scalability.",
      "State channels enable off-chain transactions.",
      "Plasma chains are layer 2 scaling solutions.",
      "Optimistic rollups assume transactions are valid.",
      "ZK-rollups use zero-knowledge proofs for validity.",
      "Validium uses off-chain data availability.",
      "Volition allows users to choose data availability.",
      "EIP-1559 reformed Ethereum's fee market.",
      "EIP-4844 introduces proto-danksharding for data availability.",
      "Danksharding is Ethereum's full sharding implementation.",
      "Proposer-Builder Separation (PBS) separates block roles.",
      "MEV-Boost allows validators to outsource block building.",
      "Account abstraction enables programmable wallets.",
      "Social recovery wallets use trusted contacts.",
      "Multi-signature wallets require multiple approvals.",
      "Threshold signatures distribute key shares.",
      "MPC (Multi-Party Computation) wallets enhance security.",
      "Hardware wallets provide cold storage security.",
      "Hierarchical Deterministic (HD) wallets generate keys from seed.",
      "BIP-39 defines mnemonic seed phrases.",
      "Elliptic curve cryptography secures most cryptocurrencies.",
      "Schnorr signatures enable signature aggregation.",
      "BLS signatures allow efficient multi-signature schemes.",
      "Verifiable Random Functions (VRFs) provide unpredictable randomness.",
      "Threshold encryption enables conditional decryption.",
      "Homomorphic encryption allows computation on encrypted data.",
      "Secure Multi-Party Computation enables joint computation.",
      "Differential privacy protects individual data in aggregates.",
      "Confidential transactions hide amounts while proving validity.",
      "Bulletproofs provide compact range proofs.",
      "STARKs offer transparency without trusted setup.",
      "Recursive SNARKs enable proof composition.",
      "Proof-carrying data allows incremental verification.",
      "Verkle trees improve Ethereum's state management.",
      "State expiry aims to bound Ethereum state growth.",
      "Address space extension increases available addresses.",
      "Stateless clients verify blocks without full state.",
      "Weak subjectivity requires social consensus for security.",
      "Long-range attacks exploit PoS by rewriting history.",
      "Nothing-at-stake problem affects naive PoS designs.",
    ]
  }
};

